import sys
import zlib
import re

# Custom Base85 charset used by Cheat Engine
CUSTOM_BASE85 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!#$%()*+,-./:;=?@[]^_{}"

def base85_decode(b85_str):
    """Decodes Cheat Engine's custom Base85 encoding into binary data."""
    size = len(b85_str)
    decoded = bytearray()
    
    i = 0
    while i < size:
        a = 0
        if i < size:
            a += CUSTOM_BASE85.index(b85_str[i]) * 85 * 85 * 85 * 85
            i += 1
        if i < size:
            a += CUSTOM_BASE85.index(b85_str[i]) * 85 * 85 * 85
            i += 1
        if i < size:
            a += CUSTOM_BASE85.index(b85_str[i]) * 85 * 85
            i += 1
        if i < size:
            a += CUSTOM_BASE85.index(b85_str[i]) * 85
            i += 1
        if i < size:
            a += CUSTOM_BASE85.index(b85_str[i])
            i += 1
            
            # 5-tuple complete
            decoded.append((a >> 24) & 0xFF)
            decoded.append((a >> 16) & 0xFF)
            decoded.append((a >> 8) & 0xFF)
            decoded.append(a & 0xFF)
            continue
            
    # Handle padding
    rem = size % 5
    if rem == 2:
        a += 84 * 85 * 85 + 84 * 85 + 84
        decoded.append((a >> 24) & 0xFF)
    elif rem == 3:
        a += 84 * 85 + 84
        decoded.append((a >> 24) & 0xFF)
        decoded.append((a >> 16) & 0xFF)
    elif rem == 4:
        a += 84
        decoded.append((a >> 24) & 0xFF)
        decoded.append((a >> 16) & 0xFF)
        decoded.append((a >> 8) & 0xFF)
        
    return bytes(decoded)

def decrypt_ce_function(b85_str):
    """Base85 decodes and then zlib decompresses a string generated by encodeFunction."""
    bin_data = base85_decode(b85_str)
    
    # Zlib decompression
    # Tcompressionstream usually includes zlib headers, so standard zlib.decompress should work
    try:
        decompressed = zlib.decompress(bin_data)
        return decompressed
    except zlib.error as e:
        print(f"Zlib decompression error: {e}")
        return None

def extract_encoded_strings(text):
    """Extracts strings that look like decodeFunction('...') arguments."""
    matches = re.finditer(r"decodeFunction\(['\"](.*?)['\"]\)", text, re.DOTALL)
    return [m.group(1) for m in matches]

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python decode_ct.py <file.txt_or_ct>")
        sys.exit(1)
        
    filename = sys.argv[1]
    with open(filename, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
        
    encoded_strings = extract_encoded_strings(content)
    print(f"Found {len(encoded_strings)} encoded functions in {filename}")
    
    for i, b85_str in enumerate(encoded_strings):
        print(f"\n--- Decoding function #{i+1} ---")
        bytecode = decrypt_ce_function(b85_str)
        if bytecode:
            out_file = f"decoded_function_{i+1}.luac"
            with open(out_file, 'wb') as out:
                out.write(bytecode)
            print(f"Successfully decoded! Saved Lua bytecode to {out_file}")
            # Optional: print first few bytes to verify it's lua bytecode
            hex_view = " ".join([f"{b:02X}" for b in bytecode[:16]])
            print(f"Header preview: {hex_view}")
            if bytecode.startswith(b'\x1bLua'):
                print("Valid Lua bytecode signature detected!")
